apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer # Changed from NodePort to LoadBalancer
  ports:
  - name: "vote-service"
    port: 80      # The port on the LoadBalancer that external traffic will hit
    targetPort: 80   # The port on the pod where the application is listening
  selector:
    app: vote
